### ISSUE TITLE
chore(deps): no vulnerabilities in the dependencies

### ISSUE THREAD

**Issue by kimyvgy** [viblo-asia/about.viblo.asia#53]
As the title, we have some vulnerabilities in the dependencies. I have yet to be able to fix these vulnerabilities. Could you please help us!

1. Fork this repository
2. Pull source code into your local
3. Check vulnerabilities with the command line:
```
# yarn
yarn audit

# npm
npm audit
```
4. Upgrade to patched dependencies & re-build this app. Please make sure that everything is working fine.
5. Open Pull Request

**Comment by jad837** [comment]
Hi I would like to work on this . Beginner here.

**Comment by jad837** [comment]
I am getting error in yarn build ReferenceError: VUE_APP_WEB_BASE_URL is not defined.

**Comment by kimyvgy** [comment]
@jad837 You can the example in `.env.example`:
```bash
cp .env.example .env
```

**Comment by jad837** [comment]
will it be ok if I open a pull request on 1 Oct under hacktoberfest ?

**Comment by kimyvgy** [comment]
@jad837 no problem
